// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwhmELB0XS6g5FvAY7E6GftsJpQppGd7I',
    appId: '1:112963516130:web:7ad02117556242fe7750bb',
    messagingSenderId: '112963516130',
    projectId: 'evently-1470e',
    authDomain: 'evently-1470e.firebaseapp.com',
    storageBucket: 'evently-1470e.firebasestorage.app',
    measurementId: 'G-M1P8FQX009',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAio9M9xhbGZWZ_nVyKU1BXW_ZTUJzksPE',
    appId: '1:112963516130:android:40d337dba1a6818d7750bb',
    messagingSenderId: '112963516130',
    projectId: 'evently-1470e',
    storageBucket: 'evently-1470e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8_IXWf2yo2S0T-0wRog_ls9WKf5YhOmo',
    appId: '1:112963516130:ios:2814a1946f4611327750bb',
    messagingSenderId: '112963516130',
    projectId: 'evently-1470e',
    storageBucket: 'evently-1470e.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8_IXWf2yo2S0T-0wRog_ls9WKf5YhOmo',
    appId: '1:112963516130:ios:2814a1946f4611327750bb',
    messagingSenderId: '112963516130',
    projectId: 'evently-1470e',
    storageBucket: 'evently-1470e.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwhmELB0XS6g5FvAY7E6GftsJpQppGd7I',
    appId: '1:112963516130:web:94fa652f93b6d18c7750bb',
    messagingSenderId: '112963516130',
    projectId: 'evently-1470e',
    authDomain: 'evently-1470e.firebaseapp.com',
    storageBucket: 'evently-1470e.firebasestorage.app',
    measurementId: 'G-2R7W5RPPQM',
  );
}
